### ISSUE TITLE
only shows the first 50 tables

### ISSUE THREAD

**Issue by mcfedr** [AntonShuvaev/intellij-dynamodb#1]
I have a project with a lot of tables, but the browser view only shows the first chunk of them (i think its 50), i can manually type queries and use the other tables, but only if i know the names

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I will fix it in the next update next week.

**Comment by AntonShuvaev** [comment]
Fixed in 2022.1.4

**Comment by mcfedr** [comment]
Awesome I'll try it out
