### ISSUE TITLE
[Bug] Filter resets every time I run a query

### ISSUE THREAD

**Issue by n12o** [AntonShuvaev/intellij-dynamodb#10]
When selecting only certain attributes to be shown upon issuing another query filter is not kept. See video below showcasing the issue:

https://user-images.githubusercontent.com/40723536/177765245-a395089c-aaeb-48db-bb35-544f588f3ca0.mp4

**Comment by n12o** [comment]
Just noticed, "reload page" button issues another query as well so you could use that to keep the filter. But ofc if you want to check the query you'd need to set the filter every time.

**Comment by AntonShuvaev** [comment]
Thanks for reporting this issue. I will fix it.

**Comment by AntonShuvaev** [comment]
Done
