### ISSUE TITLE
Assumed role not respected

### ISSUE THREAD

**Issue by tautologistics** [AntonShuvaev/intellij-dynamodb#13]
Hello,

I have the plugin configured to connect with a profile set up to use an assumed role and am able to enumerate and query tables but they are the tables in the bastion account and not the sub-account that the profile is pointed to.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/148452/183686142-97aa6724-542d-4e33-a067-1f99f7861624.png">

The enumerated list in the `DynamoDB` panel are the tables in the bastion account and not the assumed role account. 

When I list the tables with the CLI (`aws --profile=staging dynamodb list-tables`), the correct set of tables are listed.

Pertinent contents of ` ~/.aws/config`:
```
[default]
region=us-east-1

[profile main]
region=us-east-1

[profile staging]
role_arn=arn:aws:iam::############:role/OrganizationAccountAccessRole
source_profile=main
region = us-east-1
```

Pertinent contents of ` ~/.aws/credentials`:
```
[main]
aws_access_key_id = XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

[staging]
aws_access_key_id = XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by AntonShuvaev** [comment]
Hi, 

Thanks for reporting an issue. The problem is that currently only one file (config or credentials) can be selected. I will fix it.

**Comment by AntonShuvaev** [comment]
I've added ability to specify `/.aws/config` file along with `/.aws/credentials` file in 2022.2.1

**Comment by tautologistics** [comment]
That worked; thank you!
