### ISSUE TITLE
Connection test failed: java.lang.IllegalArgumentException: Expected a profile or property definition on line 2

### ISSUE THREAD

**Issue by mm-mkkm** [AntonShuvaev/intellij-dynamodb#14]
I was trying to test connection with my aws creds, apparently the connection fails.

![image](https://user-images.githubusercontent.com/81677866/191630210-22952b78-8348-4635-a22a-c29545ad15f6.png)

![image](https://user-images.githubusercontent.com/81677866/191630313-e3717118-9135-49fb-ae7f-52ecf5cc031b.png)
![image](https://user-images.githubusercontent.com/81677866/191630331-ad830479-6478-49dc-8e15-56c54d145407.png)

I tried all the 3 modes of connection, nothing seem to succeed. However, I can connect and query successfully via aws cli. Not sure what is missing.

Following is the version of the plugin I have installed.
![image](https://user-images.githubusercontent.com/81677866/191630780-46dd925b-e68f-42cd-ae40-7241a87e0e65.png)

Intellij Version:
![image](https://user-images.githubusercontent.com/81677866/191630903-027033ae-f35b-4b05-9bb9-bd7dfa1c0006.png)

Content inside my aws config/credential file looks like this. I have masked the creds for sharing:
```
[default]
    region=us-west-2
    aws_access_key_id = ****
    aws_secret_access_key = ****
```

**Comment by AntonShuvaev** [comment]
Hi, Can you try to remove indent?

**Comment by mm-mkkm** [comment]
> Hi, Can you try to remove indent?

Hooray! It did work removing the indentation. Thank you very much. 👍 

However, I would have expected it to work even otherwise or if I was using the keys(secret and access) to establish the connection, because I had profile set up as my env property.  Irrespective of profile being set as env property, it was still looking for the config inside `~/.aws`, not sure why.

Probably, some useful hint in the error message would really be helpful.
