### ISSUE TITLE
Import failed. Unable to execute HTTP request: Read timed out

### ISSUE THREAD

**Issue by rovrevik** [AntonShuvaev/intellij-dynamodb#15]
Export from localstack table (DynamoDB JSON) and then try to import the exported file back into a new table created with the same schema also exported as Create Table.

The export is only 38 meg.
After failure the target import table has only 25 of 42756 items.

**Comment by AntonShuvaev** [comment]
Could you share an example of any failed item (without sensitive data)?

**Comment by AntonShuvaev** [comment]
Closing the issue, feel free to reopen if needed
