### ISSUE TITLE
Can connect to database but no tables listed in the tree view

### ISSUE THREAD

**Issue by didjado** [AntonShuvaev/intellij-dynamodb#16]
after adding a connection and clicking the Test connection ... it comes back with successfull 

but the tree vuew never populates with anything else... not tables or anything apart from the Dynamdb icon

what am i missing

**Comment by AntonShuvaev** [comment]
Make sure that you select the correct AWS Region in connection settings and that your AWS account have a permission for ListTables operation. And can you check tables with AWS CLI `aws dynamodb list-tables`?

**Comment by AntonShuvaev** [comment]
Closing the issue, feel free to reopen if needed
