### ISSUE TITLE
DynamoDB language injection doesn't handle ? parameter placements

### ISSUE THREAD

**Issue by kitsunde** [AntonShuvaev/intellij-dynamodb#17]
Statements with `?` placeholders get flagged as invalid syntax:

```
await dynamoDB.executeStatement({
  Statement: `
          INSERT INTO "${TABLE_NAME}"
          VALUE {
            'id': ?
          }
        `,
  Parameters: [
    { S: 'test' }
  ],
}).promise();
```

![Screen Shot 2022-11-02 at 5 25 20 PM](https://user-images.githubusercontent.com/48965/199453161-d54a7721-1404-41b0-818a-48b1bdb1cf9d.png)

**Comment by AntonShuvaev** [comment]
Thanks for reporting. Will be fixed in the next release.

**Comment by AntonShuvaev** [comment]
Fixed.
