### ISSUE TITLE
!= shows up as syntax error

### ISSUE THREAD

**Issue by kitsunde** [AntonShuvaev/intellij-dynamodb#19]
Hello

```sql
SELECT * 
FROM foo
WHERE "a" != "b"
```

As seen here:

![Screen Shot 2022-11-17 at 11 04 33 PM](https://user-images.githubusercontent.com/48965/202482019-37abfabb-0664-4c47-80bf-9491d0d7b3a0.png)

Gets highlighted as an error.

It works just like `<>` despite not being documented in https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ql-operators.html

**Comment by AntonShuvaev** [comment]
Hello, thanks for reporting the issue. I will fix it in the next release.

**Comment by AntonShuvaev** [comment]
Fixed in 2022.3.4
