### ISSUE TITLE
Bad conversion of JSON null field to binary

### ISSUE THREAD

**Issue by jpJuni0r** [AntonShuvaev/intellij-dynamodb#23]
When importing the following file, I receive an invalid DyanamoDB JSON, as shown below.

```json
{
  "key": "sample",
  "key-2": null
}
```

<img width="878" alt="Screenshot 2023-01-15 at 22 36 40" src="https://user-images.githubusercontent.com/5278187/212568710-c1a68614-e508-4fb0-8b8c-f2a6d91d2a1b.png">

Note, that I manually marked the type of "key-2" as binary. I'd expect that field to be converted to `{"NULL": true}` instead instead of specifying a malicous binary value.

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I will fix it in the next update.

**Comment by jpJuni0r** [comment]
Thank you!

**Comment by AntonShuvaev** [comment]
Fixed with 2023.1.0
