### ISSUE TITLE
MFA serial in config

### ISSUE THREAD

**Issue by estoel81** [AntonShuvaev/intellij-dynamodb#24]
I have a mfa_serial defined in my config file that is connected to my user. To connect to DynamoDB, I need to enter an OTP, but the plugin doesn't give me the option to do so. Therefore I get a 403 when I try to connect. 

![image](https://user-images.githubusercontent.com/17541712/214241026-9199509b-76fb-4c28-be2b-b0f71f8cb031.png)
![image](https://user-images.githubusercontent.com/17541712/214241213-c5bfcb35-e3ce-4487-9e36-c0b85aa8fd23.png)

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I will add support for MFA in the next update.

**Comment by AntonShuvaev** [comment]
Implemented in 2022.3.5
