### ISSUE TITLE
AWS credentials process authentication not working with plugin

### ISSUE THREAD

**Issue by pmenager** [AntonShuvaev/intellij-dynamodb#25]
Cannot connect with an AWS account with a profile using credential_process (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html).
I tried the authentication type "Profile from credentials file".

**Comment by AntonShuvaev** [comment]
Hi @pmenager, what error do you get when testing connection? I've just tested it and it works fine. The only issue I had was that script file was not executable I've changed the permissions with `chmod +x`. Maybe you can try to do the same.

**Comment by pmenager** [comment]
Hi @AntonShuvaev,

Sorry I forgot to include the exception I got when I test the connection, it's truncated:

> Connection test failed: java.lang.IllegalStateException: Failed to refresh process-based credentials

If there is a file where the plugin logs exception let me know I will look at it.

**Comment by AntonShuvaev** [comment]
I found the similar issue in aws plugin https://github.com/aws/aws-toolkit-jetbrains/issues/1529. Can you try to launch IDE from terminal?

**Comment by pmenager** [comment]
That's the issue here, it work when launching the IDE from the CLI. Thank you for your help, I am closing this issue.
