### ISSUE TITLE
page size selecter bug

### ISSUE THREAD

**Issue by justinseesdragons** [AntonShuvaev/intellij-dynamodb#27]
assuming this is a bug in the page size computation logic...  it doubles the next max page size every time you select it but obviously does not fetch this amount of records.   there is no limit.
![image](https://user-images.githubusercontent.com/8757011/223756546-2ed148af-b3cf-44d7-9f35-6b93b09e7bf4.png)

**Comment by AntonShuvaev** [comment]
This is [Limit](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html#DDB-Scan-request-Limit) parameter. It can be any integer. DynamoDB reads up to the `Limit` or a maximum of 1 MB and then applies the filter. So the number of returned items can be less than the `Limit`.

**Comment by AntonShuvaev** [comment]
I'll close this issue as I don't think it's a bug. If you have any further questions, please feel free to reopen it.
