### ISSUE TITLE
Datagrip Cannot Successfully Restart With Plugin Installed

### ISSUE THREAD

**Issue by fjaccarino** [AntonShuvaev/intellij-dynamodb#31]
<img width="794" alt="Licenses" src="https://user-images.githubusercontent.com/431534/230966060-c424b6a1-62d0-437b-adad-ca878ba6041a.png">

Restarting Datagrip when the plugin is installed results in the attached modal even though the plugin is registered and there is two weeks left on the trial.  "Please register the plugin".  

<img width="765" alt="JetBrains_Account" src="https://user-images.githubusercontent.com/431534/230966400-800a6934-7a25-487d-bf08-8d1871a806c9.png">

**Comment by fjaccarino** [comment]
DataGrip 2022.3.3
Build #DB-223.8617.3, built on January 10, 2023

macOS Monterey
Version 12.6.1

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. Will fix asap.

**Comment by AntonShuvaev** [comment]
The bug is fixed. Please update to version 2023.1.4.
