### ISSUE TITLE
Not work with YDB Documents tables

### ISSUE THREAD

**Issue by 1xtr** [AntonShuvaev/intellij-dynamodb#32]
In my YC Functions I work with YDB Document tables with `@aws-sdk/client-dynamodb` and `@aws-sdk/lib-dynamodb` libs for all Cmd.
In latest PhpStorm plugin connect successfully but not open tree of content

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I will take a look at a it.

**Comment by AntonShuvaev** [comment]
The issue is fixed in version 2023.1.5.

**Comment by 1xtr** [comment]
All works fine! Thx!
