### ISSUE TITLE
What are the details of "Do not automatically execute queries from opened files after IDE restart" in the changelog?

### ISSUE THREAD

**Issue by kitsunde** [AntonShuvaev/intellij-dynamodb#33]
Hello I just saw

> Do not automatically execute queries from opened files after IDE restart

from https://github.com/AntonShuvaev/intellij-dynamodb/blob/main/CHANGELOG.md. Is there any details what would trigger that?

I have several consoles with operational ad-hoc queries, I want to understand if they've been triggering without my knowledge.

**Comment by AntonShuvaev** [comment]
Hello,

The queries from console files are not executed automatically after IDE restart.

The issue is related only to the favorite queries with enabled "Perform request after opening" and temporary files that are created by double-clicking on the table item in the explorer.
