### ISSUE TITLE
Batch Write Items to another table directly from UI

### ISSUE THREAD

**Issue by 1xtr** [AntonShuvaev/intellij-dynamodb#35]
### Is your feature request related to a problem?

I can copy items **only** through export to files

### Describe the solution you'd like

`Batch Write Item` need's  `Copy table to...` options
![image](https://github.com/AntonShuvaev/intellij-dynamodb/assets/59780048/9fe93da1-c7a7-4fd5-b91d-d62944c0dcd2)

![image](https://github.com/AntonShuvaev/intellij-dynamodb/assets/59780048/65b3b2a2-be8d-4221-8484-d1939c816a3a)

### Additional context

I have production DDB and it have some items,
For developing even I have local DDB and often need to copy some items to local table.

**Comment by AntonShuvaev** [comment]
Great suggestion! I will implement this in the future release.

**Comment by AntonShuvaev** [comment]
Released in 2023.2.2
