### ISSUE TITLE
[Suggestion] Make double-clicking on the row ID a shortcut to opening the edit window

### ISSUE THREAD

**Issue by ktwbc** [AntonShuvaev/intellij-dynamodb#38]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

You can click on a record and then the toolbar (or Command B) to open the edit window. For click connivence, you could also make the row # itself to the left of the record (highlighted in screenshot) react to a double-click to open this box.

If you wanted to take it a step further, make a user config option somewhere to have double clicking on the row anywhere open the box instead of just the single field as it does now/

<img width="504" alt="Screenshot 2023-08-19 at 12 57 12" src="https://github.com/AntonShuvaev/intellij-dynamodb/assets/624611/84ea80f1-a5cd-44de-b2f2-fc45c056e87d">

**Comment by AntonShuvaev** [comment]
Thank you for the suggestion. I will do it in the next update.

**Comment by AntonShuvaev** [comment]
I've added item editing by double-clicking on the number column, and by using Ctrl + double-click on a row.
