### ISSUE TITLE
[Suggestion] Dragging columns should be preserved if you refresh query

### ISSUE THREAD

**Issue by ktwbc** [AntonShuvaev/intellij-dynamodb#39]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

If you do a query and then drag the columns around, then do a Command+r to refresh by requerying (but not otherwise leave the screen), the column order should really be preserved. I understand if you go to other menu options and go back that it would reset to the original order, but for troubleshooting where you might want to move a column up front to focus on, and then refresh as you're doing things with the db, having that column order stick is very useful.

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion. I'll look into it.

**Comment by AntonShuvaev** [comment]
Released in 2023.2.2
