### ISSUE TITLE
Edit and see favorites?

### ISSUE THREAD

**Issue by kaisermario** [AntonShuvaev/intellij-dynamodb#4]
Hey AntonShuvaev, 

I really like your dynamodb plugin for intelliJ.
Can you explain me where the favorites are saved to?
Is there a possibility within the plugin to edit and remove favorites?

Best wishes,
Mario

**Comment by AntonShuvaev** [comment]
Hello Mario, thanks for the feedback.

The Favorites are in the Bookmarks tool window(Cmd + 2). There you can delete or edit it. But it is not possible to edit the requests, only name and parameters. Also you can open favorites in the context menu of the database explorer tree. 

Besides you can keep your favorite requests in the project or scratch files.

<img width="1312" alt="Screenshot 2022-05-19 at 10 41 32" src="https://user-images.githubusercontent.com/25157138/169240371-df35da1a-1768-47a6-85bc-77cdb6b1761a.png">

**Comment by AntonShuvaev** [comment]
I'll consider adding functionality to save favorite requests changes in the future release.
