### ISSUE TITLE
Expanding edit window doesn't expand textarea

### ISSUE THREAD

**Issue by ktwbc** [AntonShuvaev/intellij-dynamodb#40]
**Describe the bug**
When you have the edit window on a record open, expanding the window via the drag handle doesn't also open up the text editing area. See screenshot.

**Steps to reproduce**
1. edit a record
2. go to lower right of editing box
3. expand with cursor

**Expected behavior**
should also open textarea 

**Environment information:**
- OS: macos
- IDE version:
- plugin version:
<img width="911" alt="Screenshot 2023-08-20 at 08 40 08" src="https://github.com/AntonShuvaev/intellij-dynamodb/assets/624611/e048b885-1e06-4b7a-af1a-97604fa1756d">

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I'll fix it in the next version.

**Comment by AntonShuvaev** [comment]
Fixed in 2023.2.2
