### ISSUE TITLE
Login does not support AWS temporary credentals

### ISSUE THREAD

**Issue by ktwbc** [AntonShuvaev/intellij-dynamodb#41]
**Describe the bug**
On the company system, we use Okta to login into AWS, which gives us three keys to put in ~/.aws/credentials every day: aws_access_key_id, aws_secret_access_key and aws_session_token (these are STS temporary credentials good for 12 hours). 

These go into the credentials file under a header that looks like this:   [1234567890_devel] i.e. an account number an label which comes out of Okta's integration.

The AWS config file ~/.aws/config is set up to have profiles that use these and look like this:

[profile 999]
region=us-east-1
output=json
source_profile=1234567890_devel
role_arn=arn:aws:iam::1234567890:role/My-Dept-Dev-Role

this profile is set up to use the credentials in the other file.  

For cli commands, you simply do the --profile 999 just like any hardcoded profile key/secret set, it works the same. But the Dynamo plugin gives this error when picking "profile from credential file" and the 999, and clicking test:

```
Connection test failed: java.lang.IllegalStateException: Invalid profile file: Circular relationship
detected with profiles [1234567890_devel, 999].
 ```

**Steps to reproduce**
You can test this scenario without Okta by just using the aws cli to generate a set of temp credentials yourself. You will need to define a Role that has permissions to do whatever first and get the arn for it, and then from the command line:

```
aws sts assume-role --role-arn $ROLE_ARN --role-session-name  'MyTestSession'
```

then put these into aws/credentials like above and set up a config profile that points to them and the same ROLE_ARN

testing from the command line like
```
aws s3api list-buckets --profile 999
```
would confirm the credentials work and then attempt to use that same profile in the plugin.

**Expected behavior**

**Environment information:**
- OS: macos
- IDE version: webstorm
- plugin version:

courtesy of ChatGPT:
```
#!/bin/bash

# Specify your AWS profile name
AWS_PROFILE="your_profile_name"

# Specify the ARN of the IAM role you want to assume
ROLE_ARN="arn:aws:iam::123456789012:role/YourRoleName"

# Specify the session name for the assumed role session
SESSION_NAME="TemporarySession"

# Execute AWS CLI command to assume the role and get temporary credentials
TEMP_CREDENTIALS=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name $SESSION_NAME)

# Extract temporary credentials from the output
ACCESS_KEY=$(echo $TEMP_CREDENTIALS | jq -r '.Credentials.AccessKeyId')
SECRET_KEY=$(echo $TEMP_CREDENTIALS | jq -r '.Credentials.SecretAccessKey')
SESSION_TOKEN=$(echo $TEMP_CREDENTIALS | jq -r '.Credentials.SessionToken')

# Update the AWS credentials file with the temporary credentials
aws configure set aws_access_key_id $ACCESS_KEY --profile $AWS_PROFILE
aws configure set aws_secret_access_key $SECRET_KEY --profile $AWS_PROFILE
aws configure set aws_session_token $SESSION_TOKEN --profile $AWS_PROFILE

echo "Temporary credentials have been generated and updated in the AWS credentials file."
```

**Comment by ktwbc** [comment]
If it helps on bug prioritization, I was looking at this plug-in potentially for our dev team but unless it supports corporate logins like Okta, it doesn't do us any good: :-(

**Comment by AntonShuvaev** [comment]
Hello @ktwbc,

Could you please check if you have a configuration in your config file that looks like this:
```
[profile 1234567890_devel]
source_profile=1234567890_devel
```
If you do, then that's likely the source of the error. DynamoDB plugin uses the AWS SDK for authentication, which does not support profiles with a source_profile referring to itself. This circular relationship, even though supported by the AWS CLI, is not supported by AWS SDK. You can find more details in this GitHub issue: https://github.com/aws/aws-sdk-java-v2/issues/1842.

As mentioned in that issue, the recommended approach to resolve this would be to split your profile into a dedicated source_profile.

Let me know if this resolves your issue or if you have any further questions.

**Comment by ktwbc** [comment]
That was it, I must have done that troubleshooting at some point, and yes as you mention the cli just ignores it. Thank you,that is working now.
