### ISSUE TITLE
problems for export data

### ISSUE THREAD

**Issue by dmartinezbello** [AntonShuvaev/intellij-dynamodb#42]
**Describe the bug**

when you tried to export data the button is not enabled, after making several selections it is enabled but never starts the data export process

**Steps to reproduce**
make a query. 
in Icon bar select csv. 
click the download icon. 
Select the path where the data is to be extracted.
click export button

**Expected behavior**
export the data of all pages of my query

**Environment information:**
- OS: macOS Ventura 13.5.1
- IDE version:  Intellij  2023.2.1
- plugin version: 2023.2.3-221

**Comment by AntonShuvaev** [comment]
Thank you for reporting the issue.

The problem occurred when I recently added the 'Copy to Another Table' option. It runs validation check even when it's not selected.

I will fix it ASAP.  In the meantime, you can use the following workaround:

1. Set the Extractor to 'Copy to Another Table'.
2. Write anything in the 'Table' field.
3. Switch the Extractor back to 'CSV'.

This should enable the export button and allow you to proceed as expected.

**Comment by AntonShuvaev** [comment]
The issue has been fixed. Please update to version 2023.2.4.
