### ISSUE TITLE
Dynamodb local cconnection fails

### ISSUE THREAD

**Issue by djokodonev** [AntonShuvaev/intellij-dynamodb#43]
**Describe the bug**
I try to create a new local dynamodb connection
```
Connection test failed: java.lang.IllegalArgumentException: Expected a profile or property
definition on line 2
```

**Steps to reproduce**
I try to connect to a local dynamodb connection on a local docker. I can use dynamodb-admin just fine.

**Expected behavior**
I should be able to connect to a local dynamodb instance

**Environment information:**
- OS: Windows 10
- IDE version:  PyCharm 2023.2.1 (Professional Edition - Build #PY-232.9559.58, built on August 22, 2023
- plugin version: 2023.2.5-232

**Comment by AntonShuvaev** [comment]
Hi @djokodonev,

Thanks for reporting this. In the next version, I'll add an option for Local DynamoDB with just a custom endpoint. For now, use "Explicit access key and secret key" Auth type and enter any keys.
