### ISSUE TITLE
Sort results within ddb window

### ISSUE THREAD

**Issue by ktwbc** [AntonShuvaev/intellij-dynamodb#45]
### Is your feature request related to a problem?

When querying on ddb data, it would be nice to be able to sort within the window, as sort of a "local sort". For example if you have a query result of 100 items, clicking on any column heading would sort your results on that column just locally. Makes it easier to find things

### Describe the solution you'd like

-

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion. Will add it in the next version.
