### ISSUE TITLE
csv export not exporting column headers

### ISSUE THREAD

**Issue by ktwbc** [AntonShuvaev/intellij-dynamodb#46]
**Describe the bug**
When choosing export with CSV exporter, choosing the option to include headers will generate a blank line at the top as if it's inserting headers, but no actual headers. Both the preview and csv results are like this, see screenshot

**Steps to reproduce**
Choose any file and Export
CSV export
Check checkbox for header rows
<img width="683" alt="Screenshot 2023-10-04 at 1 14 56 PM" src="https://github.com/AntonShuvaev/intellij-dynamodb/assets/624611/6f1509d0-b028-4173-ab13-aeea0b6889a6">

**Expected behavior**

**Environment information:**
- OS:
- IDE version:
- plugin version:

**Comment by AntonShuvaev** [comment]
Thank you for reporting the bug. Will fix it asap.
