### ISSUE TITLE
New Sort feature not working properly with primary keys

### ISSUE THREAD

**Issue by ktwbc** [AntonShuvaev/intellij-dynamodb#47]
**Describe the bug**
On the new feature Sort results within ddb window #45 the sorting works fine for non-key columns but columns that make up up your PK or SK are not working properly.

Clicking on a non-key column will resort all the columns together which is what you would expect, to keep the record together. But clicking on the PK column will sort only that column, meaning the rows are no longer aligned.

**Steps to reproduce**
Bring up a query of 100 rows that have several columns
click on a non-key column, all sorts correctly
click on the PK column and only that column will sort

**Expected behavior**

**Environment information:**
- OS:
- IDE version:
- plugin version:

**Comment by AntonShuvaev** [comment]
Hi,

The behavior you're seeing is actually how the sorting is designed to work. When you add sorting by another column, it doesn't remove the existing sorting but applies additionally. You can see the numbers indicating the sorting priority of each column in the header. If you want to sort by a single new column, click on the initially sorted column again to remove its sorting.
