### ISSUE TITLE
Table names with  a dot are truncated in editor tabs

### ISSUE THREAD

**Issue by cmflynn** [AntonShuvaev/intellij-dynamodb#48]
**Describe the bug**
<img width="793" alt="Screenshot 2023-10-13 at 2 48 13 PM" src="https://github.com/AntonShuvaev/intellij-dynamodb/assets/18743297/e29b3f35-083b-431d-8302-3889e3b5ff9a">

those tables should be `bo.xxx`, `bo.yyy`, `audit.1234`
**Environment information:**
- OS: Mac
- IDE version: IntelliJ IDEA 2023.1 (Ultimate Edition)
- plugin version: 2023.2.7-231

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I'll fix this in the next version.
