### ISSUE TITLE
Fetching tables list takes too long

### ISSUE THREAD

**Issue by dkBrazz** [AntonShuvaev/intellij-dynamodb#49]
When opening an IDE and fetching the initial list of tables it takes two-three minutes to see the tables
In my AWS account, I have around 600 tables

I suppose the plugin fetches tables and then the metadata for each table before showing a list
Maybe it is worth splitting metadata collection into the background, with the possibility of opening a separate table in the data browser before all the metadata is gathered

**Comment by AntonShuvaev** [comment]
Thank you for reporting this issue. I will try to improve the performance by possibly implementing asynchronous table and metadata loading.

**Comment by AntonShuvaev** [comment]
In version 2023.3.0, I've improved the table list loading. The metadata now loads asynchronously. Please let me know if you're still experiencing issues.

**Comment by dkBrazz** [comment]
Tables load much faster now, thank you for such a fast fix!
