### ISSUE TITLE
Tables list search and filtering

### ISSUE THREAD

**Issue by dkBrazz** [AntonShuvaev/intellij-dynamodb#50]
### Is your feature request related to a problem?

Currently, searching by table name is not convenient, because it searches by part of the name 
If I search a table `User` it highlights lots of tables containing `User` but starting with A, B, C, etc. and I have to scroll down in any way

### Describe the solution you'd like

Tables filter
Instead of highlighting tables, I would like to have a filtered list of matching tables similar to how it is done in the AWS console in the Explore Items view

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion. Will do it in the next version.
