### ISSUE TITLE
Table Name Exclude Pattern

### ISSUE THREAD

**Issue by dkBrazz** [AntonShuvaev/intellij-dynamodb#51]
### Is your feature request related to a problem?

I have about 600 tables and many of them are archive tables which I do not need usually
These tables have specific name pattern
I would like to be able to exclude these tables from showing in the list

### Describe the solution you'd like

An additional option in Advanced similar to 'Table Name Pattern' but with Exclusion behavior would work for me

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion. Will do it in the next version.
