### ISSUE TITLE
Automatically add closing quota in Query in Data Browser

### ISSUE THREAD

**Issue by dkBrazz** [AntonShuvaev/intellij-dynamodb#53]
### Is your feature request related to a problem?

It has become a usual practice for modern IDE to automatically add closing quota/bracket/etc. while keeping the cursor between them

### Describe the solution you'd like

when I type in Query `userId = '` it should be changed to `userId = '|'` where `|` is the position of the cursor

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion. I will add it in the next version.
