### ISSUE TITLE
Plugin makes it nearly impossible to work with projects that have multiple similar named files.

### ISSUE THREAD

**Issue by nutzaalex** [AntonShuvaev/intellij-dynamodb#54]
**Describe the bug**
When having opened two or more files with the same name in webstorm IDE, the tabs from within the IDE contain the folder name for those files as well. Installing this plugin will show only the name of the file without its parent folder name, even if multiple files with the same name are opened. This makes the plugin unusable if the project you work with it also has a lot of files with the same name.

**Steps to reproduce**
Just install the plugin

**Expected behavior**
The IDE should work as before, opening two or more files with the same name should differentiate them by adding the folder name in the file tab title

**Environment information:**
- OS: Mac OS 14.2.1
- IDE version: Webstorm 2023.3.2 Build #WS-233.13135.92, built on December 19, 2023
- plugin version: 2023.3.0-233

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I'll fix it in the version.
