### ISSUE TITLE
begins_with query condition no longer allowed

### ISSUE THREAD

**Issue by benward2301** [AntonShuvaev/intellij-dynamodb#55]
I have just updated to version 2023.3.1-232 and I now get the following error when I enter `begins_with` into the query bar:

> <and query> expected, got 'begins_with'

Other conditions e.g. `attribute_exists` still work.

**Comment by AntonShuvaev** [comment]
In the recent update, I've changed the syntax for `begins_with` and `contains` expressions to enhance consistency and readability. Now, to use the `begins_with` expression, you should format it as `field begins_with 'text'` instead of the previous `begins_with(field, 'text')`
