### ISSUE TITLE
Multiple windows, not modal

### ISSUE THREAD

**Issue by michaelthwaite** [AntonShuvaev/intellij-dynamodb#58]
### Is your feature request related to a problem?

I'd like to be able to open more than one window showing a row so that I can compare and edit.

### Describe the solution you'd like

The current window is not model and double clicking on a row opens a new floating window to allow editing of two items or more.

Ideally, the editor would show the table name, primary key & hash of the item being edited to allow me to keep track of multiple windows.

### Additional context

I'm looking to view more than one row to copy/paste entries from one to the other, thanks.

**Comment by AntonShuvaev** [comment]
Thank you for the suggestion. I will consider adding this in the future release.

**Comment by AntonShuvaev** [comment]
I've added the ability to edit multiple documents simultaneously. You can now open multiple items and edit only those necessary.

**Comment by michaelthwaite** [comment]
I've updated to 2024.1.0 (2024-03-15) but still, when I open an item, it becomes model so I can't click on any other items.

I've attached a screen shot showing the region that's un-reachable, is there a switch I should throw?

<img width="1207" alt="Screenshot 2024-03-16 at 16 57 43" src="https://github.com/AntonShuvaev/intellij-dynamodb/assets/5407315/c2b99c0a-52e9-4082-a691-3515e2e4059a">

**Comment by AntonShuvaev** [comment]
I've implemented the ability to edit multiple items within a single modal window for simplicity and efficiency, rather than using multiple windows. Please select the items you wish to edit, and you will be able to work on them simultaneously in the same window. This allows you to edit only the items you need and leave the others as they are. I hope this approach meets your needs.

**Comment by michaelthwaite** [comment]
Ah, I see what you've done now. That works but if I'm honest, isn't as helpful as I'd hoped for. I'd say that I would normally find a record from the key, then find another, I'd hoped to be able to open two, side-by-side to compare differences, if possible without the windows being model so that I can copy/paste say, the output from the debug window as an example.
