### ISSUE TITLE
Query History doesn't work in DataGrip 2024.2 EAP

### ISSUE THREAD

**Issue by dkBrazz** [AntonShuvaev/intellij-dynamodb#60]
**Describe the bug**
A query from the history disappears right after choosing it

**Steps to reproduce**
Have a history of queries for the table
Open a table and click on the lens button in the query input
From the query history choose a query
A query is set into the input for a moment and then disappears

**Environment information:**
- IDE version: DataGrip 2024.2 EAP
- plugin version: 2024.1.0-242

It might be a bug in the IAP build or a change in the Idea API

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I'll fix it soon.
