### ISSUE TITLE
Cannot connect to Dynamo with profile name [Circular relationship detected]

### ISSUE THREAD

**Issue by dehad** [AntonShuvaev/intellij-dynamodb#7]
Connection test failed: java.lang.IllegalStateException: Invalid profile file: Circular relationship
detected with profiles [my-test-profile].

**Comment by AntonShuvaev** [comment]
Hi,

Can you check that your `config` or `credentials` file has no circular dependency like
```
[profile my-test-profile]
source_profile=my-test-profile
```
If so, then you need to rewrite it through two different profiles.
